spring.application.name=petlink-2026
spring.datasource.name=db_petlink
spring.datasource.base.url=jdbc:postgresql://localhost:5432/
spring.datasource.url=jdbc:postgresql://localhost:5432/${spring.datasource.name}
spring.datasource.username=postgres
spring.datasource.password=123456